services:
  network-deploy-services:  
    networks:
     - bank
  microservice-base-config:
    extends:
      service: network-deploy-services
    deploy:
      resources:
        limits:
          memory: 700m
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  microservice-db-config:
    extends:
      service: network-deploy-services
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mysql