spring:
  config:
    activate:
      on-profile:
      - "qa"

build:
  value: 2.2

loans:
  description: "This is a Loan MS which is a part of the Bank Appn: QA"
  owner:
    name: "Riyasshri"
    email: "riya@gmail.com"
  mobile:
    - 1234567890
    - 2345678901