build:
  version: "2.0"

accounts:
  message: "Welcome to the Bank Service. This is the Account MS: QA"
  contactDetails: 
    name: "Bank Manager: QA"
    email: "bankManager@bank.com"
  onCallSupport:
    - 1234567890
    - 0987654321
