build:
  value: 0.5

cards:
  description: "This is a Card MS which is a part of the Bank Appn: QA"
  owner:
    name: "Hari Baskar"
    email: "hari@gmail.com"
  mobile:
    - 1234567890
    - 2345678901